---
title: "5-2 靜態視覺化"
author: "kbjiyu"
date: "2021/10/06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1 ggplot2
> tidyverse 套件群之一。
- [官網](https://ggplot2.tidyverse.org/)
- [R Graph Gallery](https://www.r-graph-gallery.com/index.html)
- [更多R視覺化範例](https://exts.ggplot2.tidyverse.org/gallery/)

## 1.1 套件
```{r}
# library("ggplot2")
library("tidyverse")

```

## 1.2 範例
```{r}
iris_df <- iris

# 1.2.1 不分組
ggplot(
  data = iris_df,                         # 1 資料表
  aes(x=Sepal.Length, y=Sepal.Width)) +   # 2 座標軸對應之資料欄位
  geom_point(size=3, color="#69b3a2")     # 3 繪圖方式

# 1.2.2 分佈圖
ggplot(
  data = iris_df, 
  aes(x=Sepal.Length, y=Sepal.Width, color=Species)) +   
  geom_point()

# 1.2.3a facet_grid
ggplot(
  data = iris_df, 
  aes(x=Sepal.Length, y=Sepal.Width)) +   
  geom_point() + 
  facet_grid(. ~ Species) # (切rows ~ 切columns)

# 1.2.3b facet_wrap
ggplot(
  data = iris_df, 
  aes(x=Sepal.Length, y=Sepal.Width)) +   
  geom_point() + 
  facet_wrap(~Species) 

# 可以繪圖, 但是意義是?
# ggplot(iris_df, aes(x=Sepal.Length, y=Sepal.Width)) +
#   geom_line()

```

# 2 plotly
- [官網](https://plotly.com/r/)

## 2.1 套件
```{r}
# install.packages("plotly")
library(plotly)

```

## 2.2 範例
```{r}
fig <- plot_ly(
  data = iris_df,    # 1 資料表
  x = ~Sepal.Length, # 2 x軸對應 欄位
  y = ~Petal.Length, # 3 y軸對應 欄位
  color = ~Species,  # 4 顏色對應 分組
  type="scatter"     # 5 繪圖方式
)
fig

```

# 3 leaflet
- https://rstudio.github.io/leaflet/

## 3.1 套件
```{r}
# install.packages("leaflet")
library(leaflet)
library(tidyverse) # 讀範例資料用

```

## 3.2 範例1
```{r}
# 基本設定
where <- list(lng=121.4501143, lat=25.1764033)
where_popup <- 商管大樓

# 繪圖
map <- leaflet() %>%
  addTiles() %>%
  addMarkers(lng=where$lng, lat=where$lat, popup=where_popup) %>%
  setView(lng=where$lng, lat=where$lat, zoom = 10)
map

```

## 3.3 範例2
```{r}
# 讀檔
df<- read_csv("./raw/youbike.csv", show_col_types = FALSE)

# 顏色函數
set_sbiColor <- function(sbi_percent) {
  color <- ""
  if (sbi_percent <= 0.3) {
    color <- "#fd5e53" # 紅
  } else if (sbi_percent <= 0.5) {
    color <- "#ffbd69" # 橘
  } else if (sbi_percent <= 0.7) {
    color <- "#b0eacd" # 淺綠
  } else {
    color <- "#21bf73" # 深綠
  }
  return(color)
}

# 繪圖
where <- list(lng=121.52245, lat=25.0133904)

map <- leaflet() %>%
  addTiles() %>%
  setView(lng=where$lng, lat=where$lat, zoom = 10) %>%
  addCircleMarkers(
    lng = df$lng, 
    lat = df$lat, 
    label = df$站名,
    color = sapply(df$可借車佔比, set_sbiColor),
    fill = T,
    radius = 2)
map

```


# 4 練習

- 1 讀檔 "./raw/winemag-data_first150k.csv"。
- 2 篩選出  price > 0 。
- 3 以 country 分組，並計算各國家之 price 中位數。
- 4 以 該中位數進行繪圖
  - 參考 https://www.r-graph-gallery.com/267-reorder-a-variable-in-ggplot2.html
```{r}
# 讀檔
df <- read_csv("./raw/winemag-data_first150k.csv", show_col_types = FALSE)

# 處理
df1 <- df %>% 
  group_by(country) %>%
  filter(price>0) %>%
  summarise(priceMean = median(price)) %>%
  arrange(desc(priceMean)) %>%
  head(10)

# 繪圖用排序factor
df1 <- df1 %>%
  mutate(plotOrder = fct_reorder(country, desc(priceMean)))

# 繪圖
ggplot(
  data=df1,
  aes(x=plotOrder, y=priceMean)) +
  geom_bar(stat="identity", fill="#f68060", alpha=.6, width=.4) +
  coord_flip() +
  xlab("") +
  theme_bw()

```